Variables
There are ten variables in the dataset as follows:

REF (reference number). The highest REF numbers were the last entries made. They are not unique values
Company name or manufacturer
Company location (Country)
Date of review of the chocolate ratings
Origin of bean (Country)
Specific bean origin or bar name
Cocoa percent
Ingredients: Represents the number of ingredients in the chocolate; (B = Beans, S = Sugar, S* = Sweetener other than white cane or beet sugar, C = Cocoa Butter, V = Vanilla, L = Lecithin, Sa = Salt)
Most memorable characteristics
Rating

Lecithin: a natural emulsifier found in egg yolks, soybeans, and sunflower seeds. It's added to chocolate to change its texture and consistency. It keeps the cocoa butter and cream from separating and improves its flow properties.

In [ ]:
import pandas as pd

df = pd.read_csv('chocolate_bar_ratings_2022.csv')
df

,REF,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,2454,5150,U.S.A.,2019,Tanzania,"Kokoa Kamili, batch 1",76%,"3- B,S,C","rich cocoa, fatty, bready",3.25
1,2454,5150,U.S.A.,2019,Madagascar,"Bejofo Estate, batch 1",76%,"3- B,S,C","cocoa, blackberry, full body",3.75
2,2458,5150,U.S.A.,2019,Dominican Republic,"Zorzal, batch 1",76%,"3- B,S,C","cocoa, vegetal, savory",3.50
3,2542,5150,U.S.A.,2021,Fiji,"Matasawalevu, batch 1",68%,"3- B,S,C","chewy, off, rubbery",3.00
4,2542,5150,U.S.A.,2021,India,"Anamalai, batch 1",68%,"3- B,S,C","milk brownie, macadamia,chewy",3.50
...,...,...,...,...,...,...,...,...,...,...
2583,1205,Zotter,Austria,2014,Blend,Raw,80%,"4- B,S*,C,Sa","waxy, cloying, vegetal",2.75
2584,1996,Zotter,Austria,2017,Colombia,"APROCAFA, Acandi",75%,"3- B,S,C","strong nutty, marshmallow",3.75
2585,2036,Zotter,Austria,2018,Blend,"Dry Aged, 30 yr Anniversary bar",75%,"3- B,S,C","fatty, earthy, cocoa",3.00
2586,2170,Zotter,Austria,2018,Congo,Mountains of the Moon,70%,"3- B,S,C","fatty, mild nuts, mild fruit",3.25
2587,2170,Zotter,Austria,2018,Belize,Maya Mtn,72%,"3- B,S,C","muted, roasty, accessible",3.50

In [20]:
df.head()

,REF,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,2454,5150,U.S.A.,2019,Tanzania,"Kokoa Kamili, batch 1",76%,"3- B,S,C","rich cocoa, fatty, bready",3.25
1,2454,5150,U.S.A.,2019,Madagascar,"Bejofo Estate, batch 1",76%,"3- B,S,C","cocoa, blackberry, full body",3.75
2,2458,5150,U.S.A.,2019,Dominican Republic,"Zorzal, batch 1",76%,"3- B,S,C","cocoa, vegetal, savory",3.50
3,2542,5150,U.S.A.,2021,Fiji,"Matasawalevu, batch 1",68%,"3- B,S,C","chewy, off, rubbery",3.00
4,2542,5150,U.S.A.,2021,India,"Anamalai, batch 1",68%,"3- B,S,C","milk brownie, macadamia,chewy",3.50

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2588 entries, 0 to 2587
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   REF                               2588 non-null   int64
 1   Company (Manufacturer)            2588 non-null   str
 2   Company Location                  2588 non-null   str
 3   Review Date                       2588 non-null   int64
 4   Country of Bean Origin            2588 non-null   str
 5   Specific Bean Origin or Bar Name  2588 non-null   str
 6   Cocoa Percent                     2588 non-null   str
 7   Ingredients                       2501 non-null   str
 8   Most Memorable Characteristics    2588 non-null   str
 9   Rating                            2588 non-null   float64
dtypes: float64(1), int64(2), str(7)
memory usage: 202.3 KB

In [22]:
df.shape

(2588, 10)

In [29]:
df['Ingredients'].value_counts()

Ingredients
3- B,S,C          1029
2- B,S             738
4- B,S,C,L         293
5- B,S,C,V,L       184
4- B,S,C,V         141
2- B,S*             31
4- B,S*,C,Sa        20
3- B,S*,C           13
3- B,S,L             8
4- B,S*,C,V          7
5-B,S,C,V,Sa         6
1- B                 6
4- B,S,V,L           5
4- B,S,C,Sa          5
6-B,S,C,V,L,Sa       4
3- B,S,V             3
4- B,S*,V,L          3
4- B,S*,C,L          2
3- B,S*,Sa           1
2- B,C               1
5- B,S,C,L,Sa        1
Name: count, dtype: int64

In [30]:
df['Country of Bean Origin'].value_counts()

Country of Bean Origin
Venezuela             254
Peru                  248
Dominican Republic    234
Ecuador               223
Madagascar            184
                     ...
China                   1
Principe                1
Sulawesi                1
Suriname                1
DR Congo                1
Name: count, Length: 63, dtype: int64

In [31]:
df['Company (Manufacturer)'].value_counts()

Company (Manufacturer)
Soma                    57
Fresco                  39
Arete                   32
Bonnat                  30
A. Morin                29
                        ..
Vietcacao (A. Morin)     1
Vintage Plantations      1
Whittakers               1
Xocolat                  1
Zacharias                1
Name: count, Length: 593, dtype: int64

In [32]:
df['Most Memorable Characteristics'].value_counts()

Most Memorable Characteristics
spicy, cocoa                    4
creamy, nutty, cocoa            4
sweet, vanilla, cocoa           3
sweet, marshmallow              3
sandy, sweet, cocoa             3
                               ..
waxy, cloying, vegetal          1
strong nutty, marshmallow       1
fatty, earthy, cocoa            1
fatty, mild nuts, mild fruit    1
muted, roasty, accessible       1
Name: count, Length: 2545, dtype: int64

In [33]:
df.describe()

               REF  Review Date       Rating
count  2588.000000  2588.000000  2588.000000
mean   1459.185471  2014.545209     3.198319
std     773.852201     4.082722     0.444069
min       5.000000  2006.000000     1.000000
25%     820.000000  2012.000000     3.000000
50%    1470.000000  2015.000000     3.250000
75%    2122.000000  2018.000000     3.500000
max    2768.000000  2022.000000     4.000000

In [35]:
df['Cocoa Percent'].value_counts()

Cocoa Percent
70%       1070
75%        312
72%        309
65%         93
80%         90
68%         75
74%         69
73%         67
60%         46
71%         44
77%         43
85%         40
64%         37
76%         35
67%         35
66%         28
78%         22
100%        21
82%         18
55%         16
62%         16
63%         15
69%         13
90%          9
88%          8
58%          8
61%          7
81%          6
83%          5
72.50%       4
84%          4
91%          3
73.50%       2
79%          2
71.50%       2
56%          2
89%          2
99%          2
50%          1
86%          1
42%          1
60.50%       1
57%          1
46%          1
53%          1
87%          1
Name: count, dtype: int64

In [36]:
print(df['Specific Bean Origin or Bar Name'])

0                 Kokoa Kamili, batch 1
1                Bejofo Estate, batch 1
2                       Zorzal, batch 1
3                 Matasawalevu, batch 1
4                     Anamalai, batch 1
                     ...
2583                                Raw
2584                   APROCAFA, Acandi
2585    Dry Aged, 30 yr Anniversary bar
2586              Mountains of the Moon
2587                           Maya Mtn
Name: Specific Bean Origin or Bar Name, Length: 2588, dtype: str