In [2]:
# Import libraries and load datasets
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sqlite3
from wordcloud import WordCloud
from datetime import datetime #only need date, not time

df_choc = pd.read_csv('../Data/chocolate_bar_ratings_2022_cleaned.csv')
df_coffee = pd.read_csv('../Data/simplified_coffee_cleaned.csv')

In [8]:
df_choc.head()

,Company,Company Location,Review Date,Bean Origin,Bar Name,Cocoa %,Ingredients,Characteristics,Rating
0,5150,U.S.A.,2019,Tanzania,"Kokoa Kamili, batch 1",76.0,"3- B,S,C","rich cocoa, fatty, bready",3.25
1,5150,U.S.A.,2019,Madagascar,"Bejofo Estate, batch 1",76.0,"3- B,S,C","cocoa, blackberry, full body",3.75
2,5150,U.S.A.,2019,Dominican Republic,"Zorzal, batch 1",76.0,"3- B,S,C","cocoa, vegetal, savory",3.50
3,5150,U.S.A.,2021,Fiji,"Matasawalevu, batch 1",68.0,"3- B,S,C","chewy, off, rubbery",3.00
4,5150,U.S.A.,2021,India,"Anamalai, batch 1",68.0,"3- B,S,C","milk brownie, macadamia,chewy",3.50

In [4]:
df_coffee.head()

,name,roaster,roast,loc_country,origin,100g_USD,rating,review_date,review
0,Ethiopia Shakiso Mormora,Revel Coffee,Medium-Light,United States,Ethiopia,4.70,92,November 2017,"Crisply sweet, cocoa-toned. Lemon blossom, roa..."
1,Ethiopia Suke Quto,Roast House,Medium-Light,United States,Ethiopia,4.19,92,November 2017,"Delicate, sweetly spice-toned. Pink peppercorn..."
2,Ethiopia Gedeb Halo Beriti,Big Creek Coffee Roasters,Medium,United States,Ethiopia,4.85,94,November 2017,"Deeply sweet, subtly pungent. Honey, pear, tan..."
3,Ethiopia Kayon Mountain,Red Rooster Coffee Roaster,Light,United States,Ethiopia,5.14,93,November 2017,"Delicate, richly and sweetly tart. Dried hibis..."
4,Ethiopia Gelgelu Natural Organic,Willoughby's Coffee & Tea,Medium-Light,United States,Ethiopia,3.97,93,November 2017,"High-toned, floral. Dried apricot, magnolia, a..."

I decided not to merge these two DataFrames. Instead, I will change some column names in both DataFrames to match each other.  I dropped the REF column in the chocolate DataFrame because it is not relevant to this analysis.

In [10]:
new_df_ch = df_choc.rename(columns={'Company': 'company', 'Company Location': 'loc_country', 'Review Date': 'review_date', 'Bean Origin': 'origin', 'Bar Name': 'bar_name', 'Cocoa %': 'cocoa_%', 'Ingredients': 'ingredients', 'Characteristics': 'review', 'Rating': 'rating'})

In [11]:
new_df_co = df_coffee.rename(columns={'name': 'coffee_name', 'roaster': 'company', })

I created an ERD with four tables. I will now create a database.

In [12]:
conn = sqlite3.connect('../Data/choc_coffee2.db')

cc_choc_bar_df = new_df_ch[['origin', 'bar_name', 'cocoa_%', 'ingredients', 'review', 'rating']].drop_duplicates()

cc_coffee_df = new_df_co[['rating', 'origin', 'coffee_name', 'roast', 'review']].drop_duplicates()

cc_choc_country_df = new_df_ch[['company', 'loc_country', 'rating']].drop_duplicates()

cc_coffee_country_df = new_df_co[['rating', 'company', 'loc_country']].drop_duplicates()

cc_choc_bar_df.to_sql('cc_choc_bar', conn, index = False, if_exists = 'replace')
cc_coffee_df.to_sql('cc_coffee', conn, index = False, if_exists = 'replace')
cc_choc_country_df.to_sql('cc_choc_country', conn, index = False, if_exists = 'replace')
cc_coffee_country_df.to_sql('cc_coffee_country', conn, index = False, if_exists = 'replace')

conn.commit

In [13]:
# create csv files for the individual tables here
cc_choc_bar_df.to_csv('../Data/cc_choc_bar_df.csv')
cc_coffee_df.to_csv('../Data/cc_coffee_df.csv')
cc_choc_country_df.to_csv('../Data/cc_choc_country_df.csv')
cc_coffee_country_df.to_csv('../Data/cc_coffee_country_df.csv')

In [ ]:
conn.close()